on: [push]
name: build
jobs:
  runhaskell:
    name: Run Haskell
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      # things to be cached/restored:
      - name: Cache stack global package db
        id:   stack-global
        uses: actions/cache@v2
        with:
          path: ~/.stack
          key: $-stack-global-$-$
          restore-keys: |
              $-stack-global-$
      - name: Cache stack-installed programs in ~/.local/bin
        id:   stack-programs
        uses: actions/cache@v2
        with:
          path: ~/.local/bin
          key: $-stack-programs-$-$
          restore-keys: |
              $-stack-programs-$
      - name: Cache .stack-work
        uses: actions/cache@v2
        with:
          path: .stack-work
          key: $-stack-work-$-$
          restore-keys: |
              $-stack-work-$
      # end cache configuration
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
        with:
          # cabal-version: 'latest'. Omitted, but defalts to 'latest'
          enable-stack: true
          stack-version: 'latest'
      - run: stack test